development:
  adapter: postgresql
  encoding: unicode
  database: school_development
  pool: 5
  username: postgresql
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: school_test
  pool: 5
  username: postgresql
  password:
