connection: &connection
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: postgres
  password: test

development:
  <<: *connection
  database: school_development

test:
  <<: *connection
  database: school_test
